### ISSUE TITLE
Language translation suggestion

### ISSUE THREAD

**Issue by ashleygrobler04** [electrolites/electrode#5]
Hi there. I took a close look at this engine and I love what I am seeing so far. 1 Nice feature I think could be added is translation functionality that allows you to translate your game into other languages. This will allow your game to reach a wider audience I believe.
The solution I have that can make it nice and easy to work with is a json based translator. This will then allow you to add any needed custom phrases into json, basicly you can add all the required stuff into json. You just need the name of the language like "english.json" and load from it. Caching is also supported. 
For example, the json looks like this:
{"health": "You have {health} remaining"}
Can I make A PR for you to take a look at it and tell me what you think?

**Comment by dragonwolfsp** [comment]
go ahead, I do want to ad this and I am glad you brawt it to my attention

**Comment by ashleygrobler04** [comment]
Hi there, I made a pull request. Please do let me know if this could work for you, it is a translation class I wrote a while back for testing so things might not work as expected.
# How to use
If you have a json file like this, { "health": "You have {health} health remaining", "tired": "You are tired." }
You should use the translator like this:
translator = Translator()
text = translator.translate("health", "english", health=10)
text2 = translator.translate("tired", "english")
print(text)
print(text2)
I do hope this makes sence and you could find it useful!

**Comment by dragonwolfsp** [comment]
I am going to have to make a few changes to this to make it compatible and fix some issues, but once done it should theoretically work.

**Comment by dragonwolfsp** [comment]
I've made my changes, let me know if you have any other suggestions before I merge, I will wait until tomorrow and if I don't here back I will merge it in.

**Comment by ashleygrobler04** [comment]
Hi there, I love the changes. You can go ahead and merge!

**Comment by ashleygrobler04** [comment]
Also, do you think it is possible to create some discussion platform for this on github? I would love to ask some questions and would love to know where this engine is going.

**Comment by dragonwolfsp** [comment]
I may do so, but since the engine is not yet usable and is currently just a bunch of interconnected modules, I don't intend to do this at this time. Also I am closing this issue as the pull request was merged a while back.
